name: Development CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install linting tools
        run: |
          pip install flake8 autopep8

      - name: Auto-fix Python style issues
        run: autopep8 --in-place --recursive src/

      - name: Run flake8 linting
        run: flake8 src/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get current date and time (Egypt time)
        run: echo "DATE_TAG=$(TZ='Africa/Cairo' date +'%Y-%m-%d--%I-%M%p')" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/toy-flask-app:dev
            ${{ secrets.DOCKERHUB_USERNAME }}/toy-flask-app:dev-${{ env.DATE_TAG }}
